FROM python:3.11-slim

WORKDIR /app

# 构建参数：pip 源
ARG PIP_INDEX_URL=

# 安装依赖
COPY requirements-obpc.txt ./
RUN pip install --no-cache-dir -r requirements-obpc.txt ${PIP_INDEX_URL:+--index-url $PIP_INDEX_URL}

# 复制全部源码
COPY . /app/
